Allow a wider range of response codes in bulk response - resolves #31
AMWA-TV/nmos-device-connection-management pull request #43
Opened 2018-09-25 09:56 UTC by simonrankine

Settled with ^[245][0-9]{2}$ as the regex for allowable response code - do people feel this is general enough?

2018-09-25 21:32 UTC, garethsb requested changes
I can't think of a good reason that the /single responses would have resulted in 3xx or 1xx, but the problem here is that I don't think "pattern" is applicable to "integer"? See http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.3.

Can we use something like this?

```
"anyOf": [
{ "minimum": 200, "maximum": 299 },
{ "minimum": 400, "maximum": 599 }
]
```

2018-09-25 22:08 UTC, garethsb-sony commented
I've tested the "anyOf" approach at https://www.jsonschemavalidator.net/ and it seems to work as intended.

2018-09-28 09:53 UTC, simonrankine commented
That should sort it...

2018-09-28 10:00 UTC, andrewbonney approved these changes

2018-09-28 10:12 UTC, merged