Clarify how auto should be resolved
AMWA-TV/nmos-device-connection-management pull request #61
Opened 2019-02-14 11:49 UTC by simonrankine

2019-02-19 13:44 UTC, andrewbonney commented on docs/2.2. APIs - Server Side Implementation.md
> +Many transport parameters in the API may be set to "auto" in the `/staged` endpoint, to imply the Sender or Receiver should select that parameter for itself. In many cases this is a simple operation,
```suggestion
Many transport parameters in the API may be set to "auto" in the `/staged` endpoint, to imply the Sender or Receiver should select that parameter for itself. In many cases this is a simple operation, and the behaviour is very clearly defined in the relevant transport parameter schemas. For example a port number may be offset from the RTP port number by a pre-determined value. The specification makes suggestions of a sensible value for auto to resolve to, but the Sender or Receiver may choose any value permitted by the schema.
```

2019-02-20 14:50 UTC, garethsb requested changes
Thanks, Simon. I think the intent is clear and I agree with the strategy (though it means implementation work for me, sigh).

Unfortunately, I think we also need to modify the ``"description"`` strings in the schema files as well because things like "(auto = 5004)" don't indicate the implementation flexibility. Maybe adding " by default" to all of them would be enough...

2019-03-05 10:22 UTC, andrewbonney commented
It may be worth an additional clarification in here noting that 'auto' doesn't need to be included in the constraints as it's defined in the schemas for the transport types.

2019-06-12 10:27 UTC, garethsb approved these changes
LGTM.

2019-06-12 10:29 UTC, merged

2019-06-12 10:29 UTC, garethsb reviewed
LGTM.